### ISSUE TITLE
Request help integrating into project

### ISSUE THREAD

**Issue by Nathaniel-MacIver** [brucemcpherson/cGoa#1]
This is a great library for Oauth2! The requirements for my project, though, are to use code hosted internally, and not imported from gitHub. I tried putting the source code into library projects within out organization, but on runtime, the Apps Script can't define the cUseful methods. Any suggestions?

**Comment by brucemcpherson** [comment]
You can just make a copy of each of the libraries referenced. You'll find the link to each library in the dependency.md on github. You can make a copy of the cuseful library in the same way.
